apiVersion: batch/v1
kind: Job
metadata:
  name: flask-db-init
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: 393078901209.dkr.ecr.us-east-1.amazonaws.com/flask-notes-app:latest
          envFrom:
            - secretRef:
                name: flask-notes-db
          env:
            - name: RUN_DB_MIGRATIONS
              value: "true"
